package com.serifsystemworks.psxdisc;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/**
 * Minimal CUE sheet model for multi-BIN PSX discs (e.g. Darkstone).
 */
public final class CueSheet {

    public static final class FileEntry {
        public String name;       // BIN filename as written in CUE
        public String type;       // BINARY, MOTOROLA, ...
        public final List<Track> tracks = new ArrayList<>();
    }

    public static final class Track {
        public int number;
        public String mode;       // MODE2/2352, MODE1/2048, AUDIO, ...
        public int index01Frames = -1; // INDEX 01 in sectors (75/sec), -1 if missing
    }

    public final List<FileEntry> files = new ArrayList<>();
    public Path cuePath;
    public Path baseDir;

    public static CueSheet parse(Path cuePath) throws IOException {
        CueSheet cue = new CueSheet();
        cue.cuePath = cuePath.toAbsolutePath().normalize();
        cue.baseDir = cue.cuePath.getParent() != null ? cue.cuePath.getParent() : Path.of(".");
        FileEntry current = null;
        Track track = null;
        for (String raw : Files.readAllLines(cue.cuePath, StandardCharsets.ISO_8859_1)) {
            String line = raw.trim();
            if (line.isEmpty() || line.startsWith("REM")) {
                continue;
            }
            String upper = line.toUpperCase(Locale.ROOT);
            if (upper.startsWith("FILE ")) {
                current = new FileEntry();
                // FILE "name" BINARY
                int q1 = line.indexOf('"');
                int q2 = line.lastIndexOf('"');
                if (q1 >= 0 && q2 > q1) {
                    current.name = line.substring(q1 + 1, q2);
                } else {
                    String[] p = line.split("\\s+");
                    current.name = p.length > 1 ? p[1] : "unknown.bin";
                }
                if (upper.contains("BINARY")) {
                    current.type = "BINARY";
                } else if (upper.contains("MOTOROLA")) {
                    current.type = "MOTOROLA";
                } else {
                    current.type = "BINARY";
                }
                cue.files.add(current);
                track = null;
            } else if (upper.startsWith("TRACK ") && current != null) {
                track = new Track();
                String[] p = line.split("\\s+");
                track.number = Integer.parseInt(p[1]);
                track.mode = p.length > 2 ? p[2].toUpperCase(Locale.ROOT) : "MODE2/2352";
                current.tracks.add(track);
            } else if (upper.startsWith("INDEX ") && track != null) {
                String[] p = line.split("\\s+");
                if (p.length >= 3 && p[1].equals("01")) {
                    track.index01Frames = parseMmSsFf(p[2]);
                }
            }
        }
        return cue;
    }

    /** MM:SS:FF → sector frames (FF is 0-74). */
    public static int parseMmSsFf(String t) {
        String[] p = t.trim().split(":");
        int mm = Integer.parseInt(p[0]);
        int ss = Integer.parseInt(p[1]);
        int ff = Integer.parseInt(p[2]);
        return (mm * 60 + ss) * 75 + ff;
    }

    public static String formatMmSsFf(int frames) {
        int ff = frames % 75;
        int totalSec = frames / 75;
        int ss = totalSec % 60;
        int mm = totalSec / 60;
        return String.format("%02d:%02d:%02d", mm, ss, ff);
    }

    /** First data track BIN path (MODE1 or MODE2), not AUDIO. */
    public Path primaryDataBin() {
        for (FileEntry f : files) {
            for (Track t : f.tracks) {
                if (t.mode != null && t.mode.startsWith("MODE")) {
                    return baseDir.resolve(f.name);
                }
            }
        }
        // fallback first file
        if (!files.isEmpty()) {
            return baseDir.resolve(files.get(0).name);
        }
        return null;
    }

    public int sectorSizeForPrimary() {
        for (FileEntry f : files) {
            for (Track t : f.tracks) {
                if (t.mode != null && t.mode.contains("2352")) {
                    return 2352;
                }
                if (t.mode != null && t.mode.contains("2048")) {
                    return 2048;
                }
            }
        }
        return 2352;
    }

    public String toCueText(String nameSuffix) {
        StringBuilder sb = new StringBuilder();
        sb.append("REM Generated by Serif PsxDiscTool\r\n");
        for (FileEntry f : files) {
            String name = f.name;
            if (nameSuffix != null && !nameSuffix.isEmpty() && name.toLowerCase(Locale.ROOT).endsWith(".bin")) {
                int dot = name.lastIndexOf('.');
                name = name.substring(0, dot) + nameSuffix + name.substring(dot);
            }
            sb.append("FILE \"").append(name).append("\" ").append(f.type != null ? f.type : "BINARY").append("\r\n");
            for (Track t : f.tracks) {
                sb.append("  TRACK ").append(String.format("%02d", t.number)).append(" ").append(t.mode).append("\r\n");
                if (t.index01Frames >= 0) {
                    sb.append("    INDEX 01 ").append(formatMmSsFf(t.index01Frames)).append("\r\n");
                } else {
                    sb.append("    INDEX 01 00:00:00\r\n");
                }
            }
        }
        return sb.toString();
    }
}
